RSS feed parser
crypto-sentiment/crypto_sentiment_notebooks pull request #8
Opened 2022-04-21 10:30 UTC by ZakharovNerd

2022-04-21 10:52 UTC, Yorko requested changes

2022-04-21 10:52 UTC, Yorko commented on notebooks/RSS_parser.ipynb
> +        "feeds = pd.read_csv('/content/Crypto feeds.csv')\n",
Закомить этот файл плз в `data` – иначе код не воспроизводится

2022-04-21 10:52 UTC, Yorko commented on notebooks/RSS_parser.ipynb
> +{
Добавь плз заголовок с идеей, ссылкой на тикет и основными результатами, посмотри пример в любом другом нубуке

2022-04-21 10:52 UTC, Yorko commented on notebooks/RSS_parser.ipynb
> +        "news = pd.DataFrame(columns = {'title':[], 'date_published':[]})\n",
Помимо тайтлов и даты давай еще добавим источник новости, например, домен верхнего уровня

2022-04-21 10:52 UTC, Yorko commented on notebooks/RSS_parser.ipynb
> +        "убираю пустые фиды"
Это публичный репозиторий, давай тут на английском. Благо, текста немного

2022-04-21 11:13 UTC, Yorko commented
И в целом у меня не воспроизводится парсинг

К примеру, `feedparser.parse('https://coinatmradar.com/blog/feed/?x=1')` выдает "bozo_exception': xml.sax._exceptions.SAXParseException('mismatched tag'),"

2022-04-25 10:39 UTC, ZakharovNerd commented on notebooks/RSS_parser.ipynb
> +{
добавил

2022-04-25 10:39 UTC, ZakharovNerd commented on notebooks/RSS_parser.ipynb
> +        "news = pd.DataFrame(columns = {'title':[], 'date_published':[]})\n",
добавил

2022-04-26 14:24 UTC, Yorko commented
Внес свои изменения, теперь код воспроизводится

2022-04-28 07:08 UTC, Yorko approved these changes

2022-04-28 07:08 UTC, merged