add augmentation method for training dataset
crypto-sentiment/crypto_sentiment_notebooks pull request #9
Opened 2022-04-21 18:34 UTC by LinkaG

Использовала готовую библиотеку для аугментации nlpaug. 
Рассмотрела аугментаторы с обратным переводом, с подтановкой синонимов и ContextualWordEmbsAug с бертом.
Что можно улучшить - в обратном переводе попробовать другие словари. я брала из примера в репозитории этой библиотеки, но есть и другие словари. В подстановке синонимов можно изменить параметры - число генерируемых предложений и число заменяемых слов в предложении. Можно вообще попробовать другую библиотеку.

Напишите, пожалуйста, замечания по коду. Я хочу переделать так, как это сделано у Вити в активном обучении. Но мне надо разобраться немножко. Пока так.

2022-04-24 10:53 UTC, aleksandrinvictor requested changes
Я бы еще перешел на какой-нибудь один способ обучения модели для экспериментов с аугами. Либо hg, либо pl. Чтобы результаты были сравнимы и меньше кода в ноутбуке

2022-04-24 10:53 UTC, aleksandrinvictor commented on notebooks/20220409_btc_4500_titles_huggingface_pipeline-augmentation.ipynb
> +    "    init_labels: List[str] = train_labels,\n",
Использовать глобальные аргументы как аргументы по умолчанию еще и мутабельные - плохая практика. Может потянуть много багов, тк во время запуска функции не понятно в каком сотоянии сейчас train_data и train_labels

2022-04-24 10:53 UTC, aleksandrinvictor commented on notebooks/20220409_btc_4500_titles_huggingface_pipeline-augmentation.ipynb
> +    "    to_model_name='facebook/wmt19-de-en'\n",
Здесь можно добавить аргумент device="cuda" и посчитать на gpu. Время выполнения сократится примерно до 2х минут. Если считаешь на cpu, можно в функцию augment передавать параметр "num_thread"

2022-04-24 10:53 UTC, aleksandrinvictor commented on notebooks/20220409_btc_4500_titles_huggingface_pipeline-augmentation.ipynb
> +    "get_trained_model(train_data_back_translation, label_data_back_translation)"
Здесь модель учится только на аугментированных сэмплах. Обычно ауги используют, чтобы расширить обучающую выборку. Те стратегия примерно такая:

1. Выберем часть сэмплов из обучающей выборки
2. Применим аугментации к ним
3. Объединим train_data и augmented_data и обучим модель на этих данных
4. Валидируем на данных без аугов

Сделал тестовый ноутбук, см ветку experimental/aug_review

2022-04-24 10:53 UTC, aleksandrinvictor commented on notebooks/20220409_btc_4500_titles_huggingface_pipeline-augmentation.ipynb
> +    "import nltk\n",
Добавить в requirements

2022-04-24 11:09 UTC, aleksandrinvictor commented on notebooks/20220409_btc_4500_titles_huggingface_pipeline-augmentation.ipynb
> +    "get_trained_model(train_data_back_translation, label_data_back_translation)"
Обсудили. Не заметил, что исходный title тоже добавляется в list aug_text_data. Те ауги добавляются к исходным данным.

2022-04-25 08:28 UTC, Yorko approved these changes
Каких-то серьезных ошибок не заметил. Видимо, в данной задаче не помогают аугментации. Объяснить это не так просто, но из наблюдений:
 - англо-немецкие и немецко-английские переводчики очень хорошие, back-translation тут приводит  результатам почти идентичным исходным текстам. 
 - синонимы и CWEA, видать, не помогают берту, так как он уже "умеет" в синонимы, а случайные вставки делались на основе почти той же модели, что обучалась 
 - но скорее всего аугментации не так эффективны с короткими текстами

Полагаю, tf-idf-логрегу такие аугментации помогли бы лучше, но проверять не стоит

2022-11-08 13:42 UTC, merged